### ISSUE TITLE
Can't find vindinium in clojars

### ISSUE THREAD

**Issue by hswick** [ornicar/vindinium-starter-clojure#5]
When I cd into example and then run lein repl I get this error and it hangs. 

Could not find artifact vindinium:vindinium:jar:0.1.0-SNAPSHOT in clojars (https://clojars.org/repo/)
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
[example]: lein repl
Could not find artifact vindinium:vindinium:jar:0.1.0-SNAPSHOT in clojars (https://clojars.org/repo/)
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
Exception in thread "Thread-4" clojure.lang.ExceptionInfo: Could not resolve dependencies {:suppress-msg true, :exit-code 1}

I could very well be missing something. If so, I'll be more than happy to make a pull request to update the docs.

**Comment by ornicar** [comment]
hmm yeah I don't know, I haven't touched this project for years.
